GET https://hng-stage2-crud.onrender.com/api/David Reece HTTP/1.1

###
GET https://hng-stage2-crud.onrender.com/api/64fe7a45290da0010a381411 HTTP/1.1

###
GET https://hng-stage2-crud.onrender.com/api HTTP/1.1

###
POST https://hng-stage2-crud.onrender.com/api HTTP/1.1
Content-Type: application/json

{
    "name": "White Man"
}

###
POST https://hng-stage2-crud.onrender.com/api HTTP/1.1
Content-Type: application/json

{
    "name": "Dane White"
}

###
# PUT http://localhost:3000/api/64fefe1eb593d56f529c1720 HTTP/1.1
# Content-Type: application/json

# {
    
#     "name": "Morw Frank",
# }



###
PATCH  https://hng-stage2-crud.onrender.com/64fe7a69290da0010a381413 HTTP/1.1
Content-Type: application/json

{
    "name": "Mon Frank"
}


###
DELETE https://hng-stage2-crud.onrender.com/api/64fe7b2da7669194c342ab03 HTTP/1.1